# Project information
site_name: MicrobiomePlots.jl
site_description: Plotting functions for the microbiome
site_author: Kevin Bonham PhD, The BioJulia Organisation and other contributors.
site_url: https://biojulia.github.io/MicrobiomePlots.jl/

# Repository
repo_url:  https://github.com/BioJulia/MicrobiomePlots.jl

# Copyright
copyright: Copyright (c) 2017 The BioJulia Organisation

# Documentation and theme
theme: material
docs_dir: 'build'

# Options
extra:
  author:
    github: BioJulia

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

# Extensions
markdown_extensions:
  - extra
  - tables
  - fenced_code
  - codehilite
  - def_list

# Page tree
pages:
  - recipes.jl
